name: CI
on:
  release:
    types: [ published ]

jobs:
  approve1:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    environment: approve1
    name: Approve1
    steps:
      - uses: actions/checkout@v4
      - name: Description
        run: echo "Approve1"

  approve2:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    environment: approve2
    name: Approve2
    steps:
      - uses: actions/checkout@v4
      - name: Description
        run: echo "Approve2"

  deploy-prod:
    needs: [ approve1, approve2 ]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    environment: prod
    name: Check
    steps:
      - uses: actions/checkout@v4
      - name: Run commands
        run: echo "Deployed prod!"
